[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "template"
description = "Template"
version = "0.1.0"
requires-python = ">=3.13"

[project.optional-dependencies]
dev = [
    "mypy==1.15.*",
    "ruff==0.11.*",
    "pre-commit==4.2.*",
]
